/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppSettings = IDL.Record({
  'anniversaryDate' : IDL.Text,
  'friendName' : IDL.Text,
  'personalLetter' : IDL.Text,
});
export const Memories = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteMemory' : IDL.Func([IDL.Nat], [], []),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'listMemories' : IDL.Func([], [IDL.Vec(Memories)], ['query']),
  'setAppSettings' : IDL.Func([AppSettings], [], []),
  'updateMemory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppSettings = IDL.Record({
    'anniversaryDate' : IDL.Text,
    'friendName' : IDL.Text,
    'personalLetter' : IDL.Text,
  });
  const Memories = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteMemory' : IDL.Func([IDL.Nat], [], []),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'listMemories' : IDL.Func([], [IDL.Vec(Memories)], ['query']),
    'setAppSettings' : IDL.Func([AppSettings], [], []),
    'updateMemory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };